Resources:
  NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
          # Generate a name based on the stage e.g. dev-notes
          # Ease of separating difference environments (dev vs. user stage)
          TableName: ${self:custom.stage}-notes
          # Table attributes
          AttributeDefinitions:
            - AttributeName: userId
              AttributeType: S
            - AttributeName: noteId
              AttributeType: S
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: noteId
              AttributeType: RANGE
          # Set the capacity based on the stage (defined in serverless.yml)
          ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.tableThroughput}
              WriteCapacityUnits: ${self:custom.tableThroughput}
